version: "3.1"

services:
  web:
    build: .
    command: gunicorn --bind=0.0.0.0:80 wsgi:app --timeout=10000
    ports:
      - 80:80
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=postgresql://finder:finder@db:5432/scraperdb
      - DATABASE_TYPE=postgres
      - RUN_HEADLESS=True
      - REDIS_URL=redis://cache:6379
  worker:
    build: .
    command: celery -A tasks beat
    depends_on:
      - "cache"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - worker:/celery
    environment:
      - DATABASE_URL=postgresql://finder:finder@db:5432/scraperdb
      - DATABASE_TYPE=postgres
      - RUN_HEADLESS=True
      - REDIS_URL=redis://cache:6379
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=finder
      - POSTGRES_PASSWORD=finder
      - POSTGRES_DB=scraperdb

volumes:
  postgres_data:
  worker:
  cache:
    driver: local