name: Python application

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry flake8 pytest
        if [ -f poetry.lock ]; then poetry install; fi
    - name: Check Pydocs have been added
      run: |
        # stop the build if there are Pydoc style missing
        pydocstyle --count
    - name: Lint with flake8
      run: |
        # stop the build if there are flake errors
        flake8 . --count --ignore=W605,W503,W504,E501 --max-complexity=10 --statistics
    - name: Test with pytest
      run: |
        pytest