name: Python application

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        if [ -f poetry.lock ]; then poetry install; fi
    - name: Check has black formatting
      run: |
        # stop the build if black formatting not applied
        poetry run python -m black . --check
    - name: Check imports are sorted correctly
      run: |
        # stop the build if there are isort errors
        poetry run python -m isort . --check
    - name: Check Pydocs have been added
      run: |
        # stop the build if there are Pydoc style missing
        poetry run python -m pydocstyle --count
    - name: Lint with flake8
      run: |
        # stop the build if there are flake errors
        poetry run python -m flake8 . --count --statistics
    - name: Test with pytest
      run: |
        poetry run python -m pytest